networks:
  nirvana-premium_chamba_network:
    external: true

services:
  usersjobsservice1.api:
    image: usersjobsservice.api:latest
    container_name: usersjobsservice1.api
    restart: on-failure
    hostname: usersjobsservice1.api
    build:
      context: ../..
      dockerfile: core/users-jobs-service/src/Users.Jobs.Service.Api/Dockerfile
    ports:
      - 9300:8080
    networks:
      - nirvana-premium_chamba_network

  usersjobsservice2.api:
    image: usersjobsservice.api:latest
    container_name: usersjobsservice2.api
    restart: on-failure
    hostname: usersjobsservice2.api
    build:
      context: ../..
      dockerfile: core/users-jobs-service/src/Users.Jobs.Service.Api/Dockerfile
    ports:
      - 9400:8080
    networks:
      - nirvana-premium_chamba_network

  redis:
    image: redis:latest
    container_name: redis_container  
    ports:
      - 6379:6379
    networks:
      - nirvana-premium_chamba_network
